server:
  port: 5001

spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: fse
        
jwt:
  secret: skilltracker
  expiry:
  	mins: 60
  get:
    token:
      uri: /skill-tracker/signin