FROM openjdk:11-jdk-slim
MAINTAINER Poovendhan Rajendiran <rpoovendhan@gmail.com>
ADD target/skill-tracker-wservice-1.0.0.jar skill-tracker-wservice-1.0.0.jar
ENTRYPOINT ["java", "-jar", "/skill-tracker-wservice-1.0.0.jar"]
EXPOSE 5000